# Build settings

title: Jennifer Parak
email: jp@jennifer-codes.com
description:
  Jennifer Parak - Highly motivated software engineer always looking for new and exciting opportunities to make the world a better place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jennifer-codes.com" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: https://www.jennifer-codes.com
twitter_username: jenpaff
github_username:  jenpaff

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

port: 443

include: ['_includes/portfolio']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
