#-------------------------------
# Build settings

port: 8000

include: ['_includes/portfolio']

sass:
  sass_dir: assets/css
  style: :nested

#-------------------------------
# General Site Settings

title: Jennifer Parak
description: Innovation comes from people who are different. 
email: jenpaff0@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Contacts, url: '#contact'}
- {name: Work And Projects, url: '#workandprojects'}
- {name: About Me, url: '#about'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Software Engineer who is passioate about coding, machine learning, systems security and loves world peace.'
  author: 'https://plus.google.com/u/0/111679023439608822937/posts'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-81637567-1

#-------------------------------
# Introduction

intro-heading: Hi!.. I'm Jennifer...

intro: I'm a 27-year old Computer Scientist. <br> And I'm on a mission to make the <br> world a better place.<br><br>...Yeh, that's right.

#-------------------------------
# Work and Projects

projects:
- {name: Software Developer at Accenture, folder: 'proj-1', file: 'portfolio/proj-1.html'}
- {name: Port To Success, folder: 'proj-2', file: 'portfolio/proj-2.html'}
- {name: Systers, folder: 'proj-3', file: 'portfolio/proj-3.html'}
- {name: Google Summer Of Code, folder: 'proj-4', file: 'portfolio/proj-4.html'}
- {name: My First iOS App, folder: 'proj-5', file: 'portfolio/proj-5.html'}
- {name: MSc Dissertation Cracking Captchas, folder: 'proj-6', file: 'portfolio/proj-6.html'}
- {name: SE Internship at Raiffeisen Bausparkasse, folder: 'proj-7', file: 'portfolio/proj-7.html'}
- {name: What's next.., folder: 'proj-8', file: 'portfolio/proj-8.html'}

#-------------------------------
# Footer

socials:
- {icon: 'soc-google', link: 'https://plus.google.com/u/0/111679023439608822937/posts'}
- {icon: 'soc-linkedin', link: 'https://at.linkedin.com/in/jennifer-parak-aab94628'}
- {icon: 'soc-twitter', link: 'https://twitter.com/jenpaff'}
- {icon: 'soc-github', link: 'https://github.com/jenpaff'}
- {icon: 'soc-instagram soc-icon-last', link: 'https://www.instagram.com/jenpaffy'}